export const CITY_SUGGESTIONS: string[] = [
  "New York, NY",
  "Brooklyn, NY",
  "Manhattan, NY",
  "Queens, NY",
  "Bronx, NY",
  "Staten Island, NY",
  "Long Island City, NY",
  "Astoria, NY",
  "Williamsburg, NY",
  "Harlem, NY",
  "Flushing, NY",
  "Jamaica, NY",
  "Yonkers, NY",
  "Buffalo, NY",
  "Rochester, NY",
  "Syracuse, NY",
  "Albany, NY",
  "White Plains, NY",
  "New Rochelle, NY",
  "Jersey City, NJ",
  "Hoboken, NJ",
  "Newark, NJ",
  "Paterson, NJ",
  "Elizabeth, NJ",
  "Trenton, NJ",
  "Princeton, NJ",
  "Atlantic City, NJ",
  "Los Angeles, CA",
  "Long Beach, CA",
  "Santa Monica, CA",
  "Pasadena, CA",
  "Beverly Hills, CA",
  "Anaheim, CA",
  "Irvine, CA",
  "Santa Ana, CA",
  "Riverside, CA",
  "San Bernardino, CA",
  "Bakersfield, CA",
  "Fresno, CA",
  "San Francisco, CA",
  "Oakland, CA",
  "Berkeley, CA",
  "San Jose, CA",
  "Palo Alto, CA",
  "Mountain View, CA",
  "Sunnyvale, CA",
  "Santa Clara, CA",
  "San Diego, CA",
  "Sacramento, CA",
  "Santa Barbara, CA",
  "San Luis Obispo, CA",
  "Monterey, CA",
  "Napa, CA",
  "Seattle, WA",
  "Bellevue, WA",
  "Tacoma, WA",
  "Spokane, WA",
  "Olympia, WA",
  "Portland, OR",
  "Eugene, OR",
  "Salem, OR",
  "Bend, OR",
  "Austin, TX",
  "Dallas, TX",
  "Fort Worth, TX",
  "Houston, TX",
  "San Antonio, TX",
  "El Paso, TX",
  "Plano, TX",
  "Arlington, TX",
  "Corpus Christi, TX",
  "Lubbock, TX",
  "Amarillo, TX",
  "Waco, TX",
  "McAllen, TX",
  "Chicago, IL",
  "Evanston, IL",
  "Naperville, IL",
  "Aurora, IL",
  "Rockford, IL",
  "Peoria, IL",
  "Springfield, IL",
  "Denver, CO",
  "Boulder, CO",
  "Colorado Springs, CO",
  "Fort Collins, CO",
  "Aurora, CO",
  "Aspen, CO",
  "Boston, MA",
  "Cambridge, MA",
  "Somerville, MA",
  "Worcester, MA",
  "Springfield, MA",
  "Lowell, MA",
  "Quincy, MA",
  "Newton, MA",
  "Provincetown, MA",
  "Philadelphia, PA",
  "Pittsburgh, PA",
  "Allentown, PA",
  "Erie, PA",
  "Reading, PA",
  "Scranton, PA",
  "Harrisburg, PA",
  "Lancaster, PA",
  "Bethlehem, PA",
  "Washington, DC",
  "Arlington, VA",
  "Alexandria, VA",
  "Richmond, VA",
  "Virginia Beach, VA",
  "Norfolk, VA",
  "Charlottesville, VA",
  "Roanoke, VA",
  "Baltimore, MD",
  "Annapolis, MD",
  "Silver Spring, MD",
  "Rockville, MD",
  "Frederick, MD",
  "Atlanta, GA",
  "Savannah, GA",
  "Augusta, GA",
  "Athens, GA",
  "Macon, GA",
  "Columbus, GA",
  "Miami, FL",
  "Miami Beach, FL",
  "Orlando, FL",
  "Tampa, FL",
  "St. Petersburg, FL",
  "Jacksonville, FL",
  "Fort Lauderdale, FL",
  "Tallahassee, FL",
  "Gainesville, FL",
  "Key West, FL",
  "Naples, FL",
  "Sarasota, FL",
  "West Palm Beach, FL",
  "Nashville, TN",
  "Memphis, TN",
  "Knoxville, TN",
  "Chattanooga, TN",
  "Franklin, TN",
  "New Orleans, LA",
  "Baton Rouge, LA",
  "Lafayette, LA",
  "Shreveport, LA",
  "Minneapolis, MN",
  "St. Paul, MN",
  "Rochester, MN",
  "Duluth, MN",
  "Madison, WI",
  "Milwaukee, WI",
  "Green Bay, WI",
  "Madison, WI",
  "Detroit, MI",
  "Ann Arbor, MI",
  "Grand Rapids, MI",
  "Lansing, MI",
  "Flint, MI",
  "Kalamazoo, MI",
  "Traverse City, MI",
  "Cleveland, OH",
  "Columbus, OH",
  "Cincinnati, OH",
  "Toledo, OH",
  "Akron, OH",
  "Dayton, OH",
  "Phoenix, AZ",
  "Scottsdale, AZ",
  "Tempe, AZ",
  "Tucson, AZ",
  "Mesa, AZ",
  "Flagstaff, AZ",
  "Sedona, AZ",
  "Las Vegas, NV",
  "Reno, NV",
  "Henderson, NV",
  "Salt Lake City, UT",
  "Park City, UT",
  "Provo, UT",
  "Ogden, UT",
  "Kansas City, MO",
  "St. Louis, MO",
  "Springfield, MO",
  "Columbia, MO",
  "Raleigh, NC",
  "Charlotte, NC",
  "Asheville, NC",
  "Durham, NC",
  "Chapel Hill, NC",
  "Greensboro, NC",
  "Winston-Salem, NC",
  "Wilmington, NC",
  "Charleston, SC",
  "Columbia, SC",
  "Greenville, SC",
  "Myrtle Beach, SC",
  "Hilton Head, SC",
  "Providence, RI",
  "Newport, RI",
  "Hartford, CT",
  "New Haven, CT",
  "Stamford, CT",
  "Bridgeport, CT",
  "Greenwich, CT",
  "Portland, ME",
  "Bangor, ME",
  "Bar Harbor, ME",
  "Burlington, VT",
  "Montpelier, VT",
  "Manchester, NH",
  "Portsmouth, NH",
  "Concord, NH",
  "Wilmington, DE",
  "Dover, DE",
  "Indianapolis, IN",
  "Bloomington, IN",
  "Fort Wayne, IN",
  "Louisville, KY",
  "Lexington, KY",
  "Oklahoma City, OK",
  "Tulsa, OK",
  "Little Rock, AR",
  "Fayetteville, AR",
  "Birmingham, AL",
  "Huntsville, AL",
  "Montgomery, AL",
  "Mobile, AL",
  "Jackson, MS",
  "Biloxi, MS",
  "Des Moines, IA",
  "Iowa City, IA",
  "Cedar Rapids, IA",
  "Omaha, NE",
  "Lincoln, NE",
  "Wichita, KS",
  "Topeka, KS",
  "Fargo, ND",
  "Bismarck, ND",
  "Sioux Falls, SD",
  "Rapid City, SD",
  "Boise, ID",
  "Idaho Falls, ID",
  "Billings, MT",
  "Bozeman, MT",
  "Missoula, MT",
  "Cheyenne, WY",
  "Jackson, WY",
  "Anchorage, AK",
  "Fairbanks, AK",
  "Juneau, AK",
  "Honolulu, HI",
  "Maui, HI",
  "Kailua, HI",
  "Hilo, HI",
  "Albuquerque, NM",
  "Santa Fe, NM",
  "Taos, NM",
  "Charleston, WV",
  "Morgantown, WV",
  "Toronto, ON",
  "Ottawa, ON",
  "Mississauga, ON",
  "Hamilton, ON",
  "London, ON",
  "Vancouver, BC",
  "Victoria, BC",
  "Montreal, QC",
  "Quebec City, QC",
  "Calgary, AB",
  "Edmonton, AB",
  "Winnipeg, MB",
  "Halifax, NS",
];

export function searchCities(query: string, limit: number = 6): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const starts: string[] = [];
  const includes: string[] = [];
  const seen = new Set<string>();
  for (const c of CITY_SUGGESTIONS) {
    if (seen.has(c)) continue;
    seen.add(c);
    const lc = c.toLowerCase();
    if (lc.startsWith(q)) starts.push(c);
    else if (lc.includes(q)) includes.push(c);
  }
  return [...starts, ...includes].slice(0, limit);
}
